### ISSUE TITLE
Unable to launch app: "Invalid options object"

### ISSUE THREAD

**Issue by Blake-LeBlanc** [christopherjnelson/Arcadyan-5G-Web-Admin#2]
My experience with node/etc has been through a Linux VM so it's very possible I'm doing something wrong on my end when it comes to setting things up properly in the Windows 10 environment.

That said, here is the output I receive after cloning the repo and attempting to start the app.

```
>npm --version
8.15.0
```

```
F:\>cd Arcadyan-5G-Web-Admin

F:\Arcadyan-5G-Web-Admin>npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1476 packages, and audited 1477 packages in 34s

211 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

F:\Arcadyan-5G-Web-Admin>npm start

> kvd_web@0.1.0 start
> react-scripts start

Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.
```

EDIT: And yes, I did try running the `npm audit fix --force` command beforehand as well

**Comment by christopherjnelson** [comment]
Looks like we're having issues with the node proxy server that I utilized to bypass CORS. Per my comment on the other issue, I'm going to look into another solution for this tonight.  What version of node are you running?

**Comment by Blake-LeBlanc** [comment]
> Looks like we're having issues with the node proxy server that I utilized to bypass CORS. Per my comment on the other issue, I'm going to look into another solution for this tonight. What version of node are you running?

v16.17.0

And I'm running `nvm` so if I need to install another version, that's no problem at all!

**Comment by christopherjnelson** [comment]
That's the same version as my development environment, so should be all good on that front. I'll do a little more research, thanks for the help!

**Comment by christopherjnelson** [comment]
Go ahead and clone the latest commit and try to run it again. I've removed the node proxy and implemented the http-middleware module for proxy usage.

**Comment by Blake-LeBlanc** [comment]
> Owner

Yay, that did the trick, we are up and at'em! 

Thanks for such a quick turnaround!

https://c.tenor.com/kwv_MuCidz8AAAAM/yes-will-ferrell.gif

**Comment by christopherjnelson** [comment]
Appreciate the help debugging! Let me know if you run into anymore issues, I tried to give it a thorough test today but at some point you just gotta get it out there for other users to break :)

**Comment by Blake-LeBlanc** [comment]
You're welcome! Thanks for making such a useful front-end!
